### ISSUE TITLE
Labs Table

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#1]
Add in Vital Labs table

**Comment by vsmalladi** [comment]
Visualize lab values as graph in patient page

**Comment by vsmalladi** [comment]
![Screen Shot 2019-08-20 at 2 50 20 PM](https://user-images.githubusercontent.com/1130240/63379424-e8fe5b00-c359-11e9-89ff-4eb3271ea1f1.png)

**Comment by cmonnom** [comment]
Ok, I finally pushed the code so y'all can play with it. 
In the todo list:
- inline css should be made into an external file but I couldn't figure it out so I made the style inline for now
- switch ajax call to use the patient json from patient.py instead of static json from github
- use the new data format for lab results (in individual arrays)
- font awesome icons maybe?
- min/max areas for each lab result
- better color scheme
![image](https://user-images.githubusercontent.com/38848214/65786017-5781c600-e11b-11e9-87c6-2c9291707422.png)

**Comment by SenseCode** [comment]
![image](https://user-images.githubusercontent.com/38848214/65785652-82b7e580-e11a-11e9-8367-c575fa1f70e9.png)
