### ISSUE TITLE
Columns to download 

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/pandiseased#283]
What columns can be downloaded per object type. 
Only one surgery and ihc results will be shown in the patient report. This will be a bug if one patient has more than one surgery and more then one ihc result. for example patient KCEPT708IJT has more than one surgery and more than one IHC, but only one of each is shown in report view.
![image](https://user-images.githubusercontent.com/44071821/98607347-9be40d00-22ae-11eb-8be0-3def4733ca87.png)
![image](https://user-images.githubusercontent.com/44071821/98607382-ae5e4680-22ae-11eb-9b81-b17d148bc8c9.png)
![image](https://user-images.githubusercontent.com/44071821/98607449-cdf56f00-22ae-11eb-8a02-dc784ce85b27.png)

**Comment by vsmalladi** [comment]
## Patients
Download minimum information and calculated fields in columns
1. Demographics
2. Dominat Tumor
3. Imaging Present
4. Radiation Given
5. Surgery Status

## Biospecimens

1. sample_type
2. tissue_type
3. anatomic_site
4. Histologic Subtype
5. species
6. blood_component
7. Tissue Type
8. Specify Other Tissue
9. Type of fluid
10. Preservation method
11. ortho_vs_sc
12. openspecimen_id

## Surgery/Pathology
1. procedure_type
2. Nephrectomy Type
3. Tumor Size Range"
4. Histologic Subtype
5. Tumor Grade
6. t_stage
7. n_stage
8. m_stage
9. laterality
10. focaility

**Comment by SenseCode** [comment]
1. patient report: all good, but the load more botton can only load 50/60 patient, after loaded 50, click the button again, then the page will  lost. 
![image](https://user-images.githubusercontent.com/38848214/104657585-d0958b80-5686-11eb-91c6-b75230246d75.png)
2. Surgery report: still have issue with one surgery should show all the listed pathreports..(Did Venkat mean this?). Otherwise all good. 
![image](https://user-images.githubusercontent.com/38848214/104657231-3897a200-5686-11eb-94a6-61f4b1dd03c0.png)
3. Biospecimen report: seems listing differently with No. 3 biospecimen list. If this is all after your discussion, then all good. 
![image](https://user-images.githubusercontent.com/38848214/104657398-844a4b80-5686-11eb-9f03-db23c5a939f7.png)
![image](https://user-images.githubusercontent.com/38848214/104657754-266a3380-5687-11eb-88b4-61e465b43fdd.png)

Great works. @mingjiecn

**Comment by mingjiecn** [comment]
Haven't touch any code in report yet, shall we set up a new issue for this load more function?

**Comment by vsmalladi** [comment]
@mingjiecn see if its an easy fix and we can put it in this branch. If not lets setup another issue.

**Comment by mingjiecn** [comment]
@vsmalladi I just had a quick look and not sure how to fix it easily. Do you have any idea?

**Comment by vsmalladi** [comment]
Not more than you. Lets set up a new issue. Put it in 2.0
